/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package econtractapi;

import econtractapi.utility.HttpPostMultipart;
import econtractapi.utility.HttpPostRaw;
import econtractapi.utility.JSONUtil;
import econtractapi.utility.StringUtil;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class eContractAPI1 extends javax.swing.JFrame {

    /**
     * Creates new form eContractAPI
     */
    
    private static int api = 0;
   
    public eContractAPI1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cb_selectAPI = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tf_grant_type = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_client_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_client_secret = new javax.swing.JTextField();
        bt_select_file = new javax.swing.JButton();
        bt_callAPI = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_customer = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_contract = new javax.swing.JTextArea();
        tf_file_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_field = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_response = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        tf_contract_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_token = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_sign_data = new javax.swing.JTextArea();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Call API eContract");

        jLabel1.setText("Chọn API cần gọi:");

        cb_selectAPI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danh sách API", "II.1 API Login Client credentials", "II.9 API Tạo hợp đồng", "II.10 Gừi hợp đồng", "II.11 Upload và cập nhật trạng thái" }));
        cb_selectAPI.setToolTipText("Danh sách API");
        cb_selectAPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_selectAPIActionPerformed(evt);
            }
        });

        jLabel2.setText("grant_type:");

        tf_grant_type.setText("client_credentials");

        jLabel3.setText("client_id:");

        tf_client_id.setText("test.client@econtract.vnpt.vn");

        jLabel4.setText("client_secret:");

        tf_client_secret.setText("U30nrmdko76057dz5aQvV9ug0mTsqAQy");

        bt_select_file.setText("Chọn file:");
        bt_select_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_select_fileActionPerformed(evt);
            }
        });

        bt_callAPI.setText("Call");
        bt_callAPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_callAPIActionPerformed(evt);
            }
        });

        jLabel5.setText("customer:");

        ta_customer.setColumns(20);
        ta_customer.setRows(5);
        ta_customer.setText("{\n    \"email\": \"khcn0012@yopmail.com\",\n    \"sdt\": \"0888340508\",\n    \"userType\": \"CONSUMER\",\n    \"ten\": \"test tvh\",\n    \"noiCap\": \"da nang\",\n    \"tenToChuc\": \"to chuc test ne\",\n    \"mst\": \"\",\n    \"loaiGtId\": \"1\",\n    \"noiCap\": \"\",\n    \"soDkdn\": \"\",\n    \"ngayCapSoDkdn\": \"2021-12-22\",\n    \"noiCapDkkd\": \"\"\n  }");
        jScrollPane1.setViewportView(ta_customer);

        jLabel6.setText("contract:");

        ta_contract.setColumns(20);
        ta_contract.setRows(5);
        ta_contract.setText("{\n  \"autoRenew\": \"true\",\n  \"callbackUrl\": \"test url\",\n  \"contractValue\": \"20000\",\n  \"creationNote\": \"\",\n  \"endDate\": \"2021-11-17\",\n  \"flowTemplateId\": \"b611cb60-e9c0-477e-8a2c-b84a8b4c688d\",\n  \"sequence\": 2,\n  \"signFlow\": [\n    {\n      \"signType\": \"DRAFT\",\n      \"signForm\": [\n        \"OTP\",\n        \"EKYC\",\n        \"OTP_EMAIL\",\n        \"NO_AUTHEN\",\n        \"EKYC_EMAIL\",\n        \"USB_TOKEN\",\n        \"SMART_CA\"\n      ],\n      \"userId\": \"nhansu01@yopmail.com\",\n      \"sequence\": 1,\n      \"limitDate\": 3\n    },\n    {\n      \"signType\": \"APPROVE\",\n      \"signForm\": [\n        \"OTP\",\n        \"EKYC\",\n        \"OTP_EMAIL\",\n        \"NO_AUTHEN\",\n        \"EKYC_EMAIL\",\n        \"USB_TOKEN\",\n        \"SMART_CA\"\n      ],\n      \"departmentId\": \"\",\n      \"userId\": \"nhansu02@yopmail.com\",\n      \"sequence\": 2,\n      \"limitDate\": 3\n    }\n  ],\n  \"signForm\": [\n     \"NO_AUTHEN\",\n       \"OTP\",\n       \"OTP_EMAIL\"\n  ],\n  \"templateId\": \"\",\n  \"title\": \"test create ct tvh 2\",\n  \"validDate\": \"2022-09-23\",\n  \"verificationType\": \"NONE\",\n  \"fixedPosition\": false\n}");
        jScrollPane2.setViewportView(ta_contract);

        tf_file_name.setText("Ten file");
        tf_file_name.setEnabled(false);

        jLabel7.setText("fields:");

        ta_field.setColumns(20);
        ta_field.setRows(5);
        ta_field.setText("{}");
        jScrollPane3.setViewportView(ta_field);

        jLabel8.setText("Response:");

        ta_response.setColumns(20);
        ta_response.setLineWrap(true);
        ta_response.setRows(5);
        jScrollPane4.setViewportView(ta_response);

        jLabel9.setText("Contract ID:");

        jLabel10.setText("Token:");

        ta_token.setColumns(20);
        ta_token.setRows(5);
        jScrollPane5.setViewportView(ta_token);

        jLabel11.setText("data sign:");

        ta_sign_data.setColumns(20);
        ta_sign_data.setRows(5);
        ta_sign_data.setText("{\n\"SignForm\":\"OTP_EMAIL\",\n\"name\": \"Phan Ngọc Thơ\",\n\"taxCode\":\"1231231234\",\n\"provider\": \"Công Ty VNPT\",\n\"pathImg\": \"iVBORw0KGgoAAAANSUhEUgAAAZAAAAJYCAYAAABM7LCIAABym\",\n\"identifierCode\": \"1231231234\", \n\"phone\":\"0917881199\",\n\"email\":\"abc@gmail.com\",\n\"phone\":\"0917881199\",\n\"status\": \"VALID\",\n\"signType\": \"APPROVAL\",\n\"ekycInfo\": \"APPROVAL\"\n}");
        jScrollPane6.setViewportView(ta_sign_data);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf_grant_type, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_client_id, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_client_secret, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                    .addComponent(cb_selectAPI, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane6)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(tf_file_name)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_contract_id))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_select_file)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_callAPI)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_selectAPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_select_file)
                    .addComponent(bt_callAPI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_grant_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_file_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_client_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tf_contract_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_client_secret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane5)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_selectAPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_selectAPIActionPerformed
        // TODO add your handling code here:
        if(cb_selectAPI.getSelectedItem() != null)
        {
            switch(cb_selectAPI.getSelectedIndex())
            {
                case 0 -> {
                    ta_customer.setEnabled(false);
                    ta_contract.setEnabled(false);
                    ta_field.setEnabled(false);
                    ta_sign_data.setEnabled(false);
                    tf_grant_type.setEnabled(false);
                    tf_client_id.setEnabled(false);
                    tf_client_secret.setEnabled(false);
                    bt_select_file.setEnabled(false);
                }
                case 1 -> {
                    api = 1;
                    ta_customer.setEnabled(false);
                    ta_contract.setEnabled(false);
                    ta_field.setEnabled(false);
                    tf_contract_id.setEnabled(false);
                    ta_token.setEnabled(false);
                    ta_sign_data.setEnabled(false);
                    tf_grant_type.setEnabled(true);
                    tf_client_id.setEnabled(true);
                    tf_client_secret.setEnabled(true);
                    bt_select_file.setEnabled(false);
                }
                case 2 -> {
                    api = 9;
                    ta_customer.setEnabled(true);
                    ta_contract.setEnabled(true);
                    ta_field.setEnabled(true);
                    ta_sign_data.setEnabled(false);
                    tf_grant_type.setEnabled(false);
                    tf_client_id.setEnabled(false);
                    tf_client_secret.setEnabled(false);
                    bt_select_file.setEnabled(true);
                }
                case 3 -> {
                    api = 10;
                    ta_customer.setEnabled(false);
                    ta_contract.setEnabled(false);
                    ta_field.setEnabled(false);
                    ta_token.setEnabled(true);
                    tf_contract_id.setEnabled(true);
                    ta_sign_data.setEnabled(false);
                    tf_grant_type.setEnabled(false);
                    tf_client_id.setEnabled(false);
                    tf_client_secret.setEnabled(false);
                    bt_select_file.setEnabled(false);
                }
                case 4 -> {
                    api = 11;
                    ta_customer.setEnabled(false);
                    ta_contract.setEnabled(false);
                    ta_field.setEnabled(false);
                    tf_grant_type.setEnabled(false);
                    ta_sign_data.setEnabled(true);
                    ta_token.setEnabled(true);
                    tf_contract_id.setEnabled(true);
                    tf_client_id.setEnabled(false);
                    tf_client_secret.setEnabled(false);
                    bt_select_file.setEnabled(true);
                }
            }
        
        }
    }//GEN-LAST:event_cb_selectAPIActionPerformed

    private void bt_callAPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_callAPIActionPerformed
        // TODO add your handling code here:
        if(api != 0)
        {
            switch(api){
                case 1 -> {
                    ta_response.setText("");
                    String inputJSON = "{\n" +
                        "    \"grant_type\": \""+tf_grant_type.getText()+"\",\n" +
                        "    \"client_id\": \""+tf_client_id.getText()+"\",\n" +
                        "    \"client_secret\": \""+tf_client_secret.getText()+"\"\n" +
                        "}";
                    //ta_response.append(api1(inputJSON));
                    api1(inputJSON);
                }
                case 9 -> {
                    if(ta_token.getText().length() == 0){
                        JOptionPane.showMessageDialog(null, "Chưa nhập token!!!", "Cảnh báo", 1);
                    } else {
                        ta_response.setText("");
                        api9("Bearer " + ta_token.getText());
                    }
                    
                }
                case 10 -> {
                    if(tf_contract_id.getText().length() == 0){
                        JOptionPane.showMessageDialog(null, "Chưa nhập Contract ID!!!", "Cảnh báo", 1);
                    } else {
                        if(ta_token.getText().length() == 0){
                        JOptionPane.showMessageDialog(null, "Chưa nhập token!!!", "Cảnh báo", 1);
                        } else {
                            ta_response.setText("");
                            System.out.println("Bearer " + ta_token.getText());
                            api10("Bearer " + ta_token.getText(), tf_contract_id.getText());
                        }
                        
                    }
                }
                case 11 -> {
                    if(ta_token.getText().length() == 0){
                        JOptionPane.showMessageDialog(null, "Chưa nhập token!!!", "Cảnh báo", 1);
                    } else {
                        if(ta_sign_data.getText().length() == 0) {
                            JOptionPane.showMessageDialog(null, "Chưa nhập data ký sô!!!", "Cảnh báo", 1);
                        } else {
                            if(tf_file_name.getText().length() == 0) {
                                JOptionPane.showMessageDialog(null, "Chưa chọn file đã ký số!!!", "Cảnh báo", 1);
                            } else {
                                ta_response.setText("");
                                //System.out.println("Bearer " + ta_token.getText());
                                api11("Bearer " + ta_token.getText(), tf_contract_id.getText());
                            }
                        }                        
                    }
                }
            }
        }      
    }//GEN-LAST:event_bt_callAPIActionPerformed

    private void bt_select_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_select_fileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File file = fc.getSelectedFile();
        String path = StringUtil.Separator(file.toPath().toString());
        this.tf_file_name.setText(path);
    }//GEN-LAST:event_bt_select_fileActionPerformed

    private void api1(String inputJson){
        try {
            HttpPostRaw post = new HttpPostRaw("https://apigateway-econtract-staging.vnptit3.vn/auth-service/oauth/token", "utf-8");
            //String json = "{\"id\":\"288285\",\"value\":\"test\"}";
            post.setPostData(inputJson);
            post.addHeader("Content-Type", "application/json");
            String out = post.finish();
            ta_response.setText(out);
            ta_token.setText(JSONUtil.getElementJSON(out,"access_token"));
        } catch (Exception e) {
            ta_response.setText("Server returned non-OK status");
            e.printStackTrace();
        }
    }
    
    private void api9(String token){
        String response = "Server returned non-OK status";
        try {
            // Set header
            Map<String, String> headers = new HashMap<>();
            headers.put("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36");
            headers.put("Authorization", token);
            HttpPostMultipart multipart = new HttpPostMultipart("https://apigateway-econtract-staging.vnptit3.vn/esolution-service/contracts/create-draft-from-file-raw", "utf-8", headers);
            // Add form field
            multipart.addFormField("customer", ta_customer.getText());
            multipart.addFormField("contract", ta_contract.getText());
            multipart.addFormField("fields", ta_field.getText());
            // Add file
            multipart.addFilePart("", new File(tf_file_name.getText()));
            // Print result
            response = multipart.finish();
            ta_response.append(response);
        } catch (Exception e) {
            ta_response.append(response);
            e.printStackTrace();
        }
    }
    
    private void api10(String token, String contractID){
        String out = "Server returned non-OK status";
        try {
            String url = "https://apigateway-econtract-staging.vnptit3.vn/esolution-service/contracts/"+contractID+"/submit-contract";
            HttpPostRaw post = new HttpPostRaw(url, "utf-8");
            //String json = "{\"id\":\"288285\",\"value\":\"test\"}";
            post.setPostData("");
            post.addHeader("Content-Type", "application/json");
            post.addHeader("Authorization", token);
            out = post.finish();
            ta_response.setText(out);
        } catch (Exception e) {
            ta_response.setText(out);
            e.printStackTrace();
        }
    }
    
    private void api11(String token, String contractID){
        String response = "Server returned non-OK status";
        try {
            // Set header
            String url = "https://apigateway-econtract-staging.vnptit3.vn/esolution-service/contracts/"+contractID+"/digital-sign";
            Map<String, String> headers = new HashMap<>();
            headers.put("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36");
            headers.put("Authorization", token);
            System.out.println(token);
            HttpPostMultipart multipart = new HttpPostMultipart(url, "utf-8", headers);
            // Add file
            multipart.addFilePart("file", new File(tf_file_name.getText()));
            // Add form field
            multipart.addFormField("data", ta_sign_data.getText());            
            // Print result
            response = multipart.finish();
            ta_response.append(response);
        } catch (Exception e) {
            ta_response.append(response);
            e.printStackTrace();
        }
    }
    
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eContractAPI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eContractAPI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eContractAPI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eContractAPI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eContractAPI1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_callAPI;
    private javax.swing.JButton bt_select_file;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cb_selectAPI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea ta_contract;
    private javax.swing.JTextArea ta_customer;
    private javax.swing.JTextArea ta_field;
    private javax.swing.JTextArea ta_response;
    private javax.swing.JTextArea ta_sign_data;
    private javax.swing.JTextArea ta_token;
    private javax.swing.JTextField tf_client_id;
    private javax.swing.JTextField tf_client_secret;
    private javax.swing.JTextField tf_contract_id;
    private javax.swing.JTextField tf_file_name;
    private javax.swing.JTextField tf_grant_type;
    // End of variables declaration//GEN-END:variables
}
